# Generated by Django 3.0.5 on 2021-11-23 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Напишите наименование автомобиля', max_length=200, verbose_name='Наименование автомобиля')),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('price', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(1)])),
                ('image', models.FileField(blank=True, upload_to='')),
                ('year', models.PositiveSmallIntegerField(help_text='Укажите год выпуска автомобиля', verbose_name='Год выпуска автомобиля')),
                ('text', models.TextField(help_text='Добавьте сюда описание автомобиля', verbose_name='Описание автомобиля')),
            ],
            options={
                'verbose_name': ('Автомобиль',),
                'verbose_name_plural': 'Автомобили',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка автомобиля')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelscar.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название ингредиента', max_length=200, verbose_name='Название комплектации')),
                ('text', models.TextField(help_text='Добавьте сюда описание комплектации', verbose_name='Описание комплектации')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelscar.Cars', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': ('Комплектация',),
                'verbose_name_plural': 'Комплектации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название цвета', max_length=200, verbose_name='Название цвета автомобиля')),
                ('color', models.CharField(help_text='HEX color, as #RRGGBB', max_length=7, verbose_name='Color')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelscar.Cars', verbose_name='Автомобиль')),
            ],
        ),
    ]
